/* Generated By:JavaCC: Do not edit this line. PigletParserConstants.java */
public interface PigletParserConstants {

  int EOF = 0;
  int LPAREN = 6;
  int RPAREN = 7;
  int LBRACE = 8;
  int RBRACE = 9;
  int LSQPAREN = 10;
  int RSQPAREN = 11;
  int DOT = 12;
  int LT = 13;
  int LE = 14;
  int GT = 15;
  int GE = 16;
  int NE = 17;
  int EQ = 18;
  int PLUS = 19;
  int MINUS = 20;
  int AND = 21;
  int OR = 22;
  int NOT = 23;
  int TIMES = 24;
  int MAIN = 25;
  int CODE = 26;
  int HALLOCATE = 27;
  int END = 28;
  int NOOP = 29;
  int MOVE = 30;
  int CALL = 31;
  int ERROR = 32;
  int PRINT = 33;
  int BEGIN = 34;
  int RETURN = 35;
  int JUMP = 36;
  int CJUMP = 37;
  int HSTORE = 38;
  int HLOAD = 39;
  int MEM = 40;
  int TEMP = 41;
  int ARG = 42;
  int INTEGER_LITERAL = 43;
  int IDENTIFIER = 44;
  int LETTER = 45;
  int DIGIT = 46;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"LT\"",
    "\"LE\"",
    "\"GT\"",
    "\"GE\"",
    "\"NE\"",
    "\"EQ\"",
    "\"PLUS\"",
    "\"MINUS\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TIMES\"",
    "\"MAIN\"",
    "\"CODE\"",
    "\"HALLOCATE\"",
    "\"END\"",
    "\"NOOP\"",
    "\"MOVE\"",
    "\"CALL\"",
    "\"ERROR\"",
    "\"PRINT\"",
    "\"BEGIN\"",
    "\"RETURN\"",
    "\"JUMP\"",
    "\"CJUMP\"",
    "\"HSTORE\"",
    "\"HLOAD\"",
    "\"MEM\"",
    "\"TEMP\"",
    "\"ARG\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
